GET http://localhost:3000/states/
###

GET http://localhost:3000/states/:stateId/
###

GET http://localhost:3000/districts/:districtId/ 
###

POST http://localhost:3000/districts/
###

DELETE http://localhost:3000/districts/:districtId/ 
###

PUT http://localhost:3000/districts/:districtId/ 
###

GET http://localhost:3000/states/:stateId/stats 
###

GET http://localhost:3000/districts/:districtId/details/